### PR TITLE
Revert indexes creation and add organization filters

### LINKED ISSUE #257: Search feature : displaying results for other organizations and not using indexes
**Describe the bug**
1) Search feature is currently not "organization safe", as there is no filter/condition on the organization id, results can include items from other organizations including not related ones.
2) Indexes created are used by generated queries
3) Searches for vehicles using "VL" or "VPSP" not working

**To Reproduce**
1. Login as an organization
2. Use search features from the dashboard/home

**Expected behavior**
1. Results from other organizations should be excluded ( expect parent organization usecase ) 
2. Indexes should be used or deleted 
3. Searches should include the type field 

**Additional context**

Current SQL Query generated : 
```
SELECT u0_.id AS id_0, u0_.identification_number AS identification_number_1, u0_.email_address AS email_address_2, u0_.first_name AS first_name_3, u0_.last_name AS last_name_4, u0_.phone_number AS phone_number_5, u0_.birthday AS birthday_6, u0_.occupation AS occupation_7, u0_.organization_occupation AS organization_occupation_8, u0_.skill_set AS skill_set_9, u0_.vulnerable AS vulnerable_10, u0_.fully_equipped AS fully_equipped_11, u0_.organization_id AS organization_id_12 
FROM users u0_ 
WHERE LOWER(u0_.first_name) LIKE LOWER('%user%') OR LOWER(u0_.last_name) LIKE LOWER('%user%') OR LOWER(u0_.email_address) LIKE LOWER('%user%') OR LOWER(u0_.identification_number) LIKE LOWER('%user%') 
LIMIT 10;
```

Explain 

```
QUERY PLAN
Limit  (cost=0.00..0.53 rows=10 width=138)
  ->  Seq Scan on users u0_  (cost=0.00..20.70 rows=390 width=138)
        Filter: ((lower((first_name)::text) ~~ '%user%'::text) OR (lower((last_name)::text) ~~ '%user%'::text) OR (lower((email_address)::text) ~~ '%user%'::text) OR (lower((identification_number)::text) ~~ '%user%'::text))
```

we should see something like "Index Scan using {indexName} on {tableName} .... "  but PostgreSQL do not use indexes for LIKE queries.

### PR DESCRIPTION
**Pull request by fmeynard**
Close #257

### CODE REVIEW

File: src/Repository/CommissionableAssetRepository.php [hunk 1]
```diff
@@ -29,13 +29,22 @@ public function __construct(ManagerRegistry $registry)
...
      * @return CommissionableAsset[]
      */
-    public function search(string $query): array
+    public function search(Organization $organization, string $query): array
     {
         $words = explode(' ', $query);
-        $qb = $this->createQueryBuilder('ca')->innerJoin('ca.organization', 'o');
+        $qb = $this->createQueryBuilder('ca');
+
+        if ($organization->isParent()) {
```
Comment (mRoca) [inline src/Repository/CommissionableAssetRepository.php:37]: I think you can remove this test, as it's also doing an sql request in order to check if the orgranization has children or not

File: src/Controller/Organization/SearchController.php [hunk 2]
```diff
@@ -4,20 +4,28 @@
...
  * @Route("/search", name="app_organization_search", methods={"GET"})
  */
 final class SearchController extends AbstractController
 {
-    public function __invoke(Request $request, UserRepository $userRepository, CommissionableAssetRepository $commissionableAssetRepository): Response
+    public function __invoke(Request $request, UserRepository $userRepository, CommissionableAssetRepository $commissionableAssetRepository, OrganizationRepository $organizationRepository): Response
     {
+        $organization = $this->getUser();
+        if (!$organization instanceof Organization) {
+            throw new AccessDeniedException();
```
Comment (vincentchalamon) [inline src/Controller/Organization/SearchController.php:26]: Should be handled in security.yaml file

File: src/Migrations/Version20200411130257.php [hunk 3]
```diff
@@ -0,0 +1,45 @@
...
+
+declare(strict_types=1);
+
+namespace DoctrineMigrations;
+
+use Doctrine\DBAL\Schema\Schema;
+use Doctrine\Migrations\AbstractMigration;
+
+/**
+ * Auto-generated Migration: Please modify to your needs!
```
Comment (vincentchalamon) [inline src/Migrations/Version20200411130257.php:11]: Please remove this automatic comment

File: src/Controller/Organization/SearchController.php (hunk 2 above)
Comment (mRoca) [reply src/Controller/Organization/SearchController.php:26]: we could need it for the user entity typehint. Maybe we can create a trait with `getOrganizationUser(): Organization` and `getUserUser(): User` ?

Comment (vincentchalamon) [reply src/Controller/Organization/SearchController.php:26]: If it's just for the typehint, it could be solved like:
```php
/** @var Organization $organization */
$organization = $this->getUser();
```

The AccessDeniedException should be handled by the security.yml, as most of access control securities of a Symfony project

Comment (mRoca) [reply src/Controller/Organization/SearchController.php:26]: I'm not a big fan of phpdoc typehint, but I'm okay for using the security component

File: src/Migrations/Version20200411130257.php (hunk 3 above)
Comment (fmeynard) [reply src/Migrations/Version20200411130257.php]: We have removed both migrations after a discussion with @mRoca to avoid run both for no reason in production
